### ISSUE TITLE
is there any working demo ?

### ISSUE THREAD

**Issue by rawmaterials** [pinry/pinry#124]
thanks

**Comment by overshard** [comment]
Not at the moment

**Comment by lapo-luchini** [comment]
I just created a [public demo website](https://pinry-demo.lapo.it/) on my server.
@overshard, any suggestion how to limit spam?

**Comment by philiptruax** [comment]
> 
> 
> I just created a [public demo website](https://pinry-demo.lapo.it/) on my server.
> @overshard, any suggestion how to limit spam?

This might be better handled with screenshots or a video for the time being due to the resources involved in maintaining, updating, and securing the site. While you can see what it looks like and click on the images without an actual walkthrough that people users can experience the other options might add more clarity.

**Comment by overshard** [comment]
There are a couple of demos up and a screenshots page on the docs if you'd like to contribute screenshots to it!

http://docs.getpinry.com/#demo-site
http://docs.getpinry.com/screenshots/
