### ISSUE TITLE
[question] default login / password (or login error)

### ISSUE THREAD

**Issue by roipoussiere** [pinry/pinry#138]
I followed installations instructions and I don't really understand what is the default login and password.

I tried the classical `admin/admin` and `root/root` and tried to run `./start_docker_with_current_user.sh`, but I get a 500 error *Something went wrong! If you figure out what it was please submit an issue on Pinry's GitHub Issue's page.* every time.

Also, Firefox console says *Failed loading for the element <script> whose source is http://127.0.0.1:2048/static/CACHE/js/75740e59b462.js*.

Did I miss something?

**Comment by winkidney** [comment]
Would you please provide information about  your environment(such OS version, what steps you have followed, etc).

Thanks : )

**Comment by winkidney** [comment]
And, would you please provide some logs from dockerd?

U could use `docker logs <container-id>` to see what happened and paste the error log here.

**Comment by winkidney** [comment]
Otherwise, in normal case, you will be asked to create a new admin user if no user exists.

**Comment by winkidney** [comment]
Feel sorry for your failure, I found that your failure is caused by operations which following this project (and this guide is for development only).

You could use https://github.com/pinry/docker-pinry to install your own instance of Pinry.

I Will add some description for this project and redirect users to project docker-pinry : )

**Comment by winkidney** [comment]
No further comment ,closed.
Please reopen it if you have any further problem on setting up Pinry.
