### ISSUE TITLE
[Question] Docker image without nginx and mysql

### ISSUE THREAD

**Issue by lonix1** [pinry/pinry#206]
I want to run the official docker image but without [nginx](https://github.com/pinry/pinry/blob/master/Dockerfile.autobuild#L47) (host already runs nginx) and without [mysql](https://github.com/pinry/pinry/blob/master/Dockerfile.autobuild#L27) (I prefer to keep it simple with sqlite).

I planned to create a custom Dockerfile, based on the official image (`getpinry/pinry`). Unfortunately I'm not a python developer, so I'm not sure what I need to leave and take out of [the Dockerfile](https://github.com/pinry/pinry/blob/master/Dockerfile.autobuild).

The alternative is to create a custom docker image, using the [instructions here](https://docs.getpinry.com/install-with-docker/#why-include-nginx-and-not-just-map-to-gunicorn-directly). It says to exclude nginx and map gunicorn, but I'm not a python dev, so I'm not sure.

Any hints?

**Comment by winkidney** [comment]
I'd like to suggest you using our development docker image instead.

+ Clone the repo and cd to it
+ Install `docker-compose`
+ `cp docker-compose.example.yml docker-compose.yml`
+ change the `SECRET_KEY` to your own
+ `cp touch pinry/settings/local_settings.py` and set `DEBUG = False` (mostly it is enough for us)
+ Run command `docker-compose build web` and the development image will be created
+ The image will use the local source code instead of built them into docker image, so you could change any code as you wish
+ Run `docker-compose up build-frontend` to build static files
+ Copy all of the files in `pinry-spa/dist/` to your nginx static root
+ Create symbol link for pinry's static folder in pinry/static/ to your nginx static root
+ Run `docker-compose up web` to start gunicorn server, it will automatically map 8080 to your localhost
+ Link your nginx to port 8080 and the static root
+ If no permission issue occurs, Pinry will work now.

**Comment by lonix1** [comment]
Thank you very much for the detailed instructions! 😃
