### ISSUE TITLE
max image url length

### ISSUE THREAD

**Issue by rhetr** [pinry/pinry#227]
why is the max image url length 256? A lot of images have very long URLs eg youtube thumbnails.

**Comment by winkidney** [comment]
@rhetr Thanks, Maybe we could make it longer.
Will be 512 after changes applied.

**Comment by winkidney** [comment]
@rhetr done, you could update to latest version of Pinry, the migration should be applied automatically.
The max-length of url will be 512 now.

**Comment by XenGi** [comment]
Even 512 is too small. I can't add an image from deviantart because it's longer then 512:
https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1daa8576-72ca-43ca-b428-0ad88450a32a/dazr2m3-6edec03c-6df1-4fd0-8891-56a38ccebd3f.jpg/v1/fill/w_600,h_887,q_75,strp/88___it_s_been_so_long_by_vashperado_dazr2m3-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD04ODciLCJwYXRoIjoiXC9mXC8xZGFhODU3Ni03MmNhLTQzY2EtYjQyOC0wYWQ4ODQ1MGEzMmFcL2RhenIybTMtNmVkZWMwM2MtNmRmMS00ZmQwLTg4OTEtNTZhMzhjY2ViZDNmLmpwZyIsIndpZHRoIjoiPD02MDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.5t2ukLn-2Cy2ysb8Suxud0q05ZOro4cqD1_80H2DJHM
